apiVersion: v1
kind: Pod
metadata:
  name: node-rabbit
  labels:
    app: web
  spec:
    containers:
      - name: some-rabbit
        image: rabbitmq:3
        ports:
          - containerPort: 5672
      - name: node-web-app
        image: emiru84/node-web-app
        ports: 
          - containerPort: 3000